"""Artifact readers for the Report Generator."""

import json
from pathlib import Path
from typing import Any

from securevibes_mcp.storage import ScanStateManager


class SecurityDocReader:
    """Reader for SECURITY.md artifact.

    Reads the security documentation generated by the assessment phase.
    """

    ARTIFACT_NAME = "SECURITY.md"

    def __init__(self, root_path: Path) -> None:
        """Initialize the reader.

        Args:
            root_path: Root path of the project.
        """
        self.root_path = root_path
        self.storage = ScanStateManager(root_path)

    def read(self) -> str | None:
        """Read the SECURITY.md artifact.

        Returns:
            Raw Markdown content as string, or None if not found.
        """
        return self.storage.read_artifact(self.ARTIFACT_NAME)

    def exists(self) -> bool:
        """Check if the artifact exists.

        Returns:
            True if the artifact exists, False otherwise.
        """
        return self.storage.artifact_exists(self.ARTIFACT_NAME)


class DASTValidationReader:
    """Reader for DAST_VALIDATION.json artifact.

    Reads the DAST validation results from the dynamic testing phase.
    """

    ARTIFACT_NAME = "DAST_VALIDATION.json"

    def __init__(self, root_path: Path) -> None:
        """Initialize the reader.

        Args:
            root_path: Root path of the project.
        """
        self.root_path = root_path
        self.storage = ScanStateManager(root_path)

    def read(self) -> dict[str, Any] | None:
        """Read the DAST_VALIDATION.json artifact.

        Returns:
            Parsed JSON content as dictionary, or None if not found or invalid.
        """
        content = self.storage.read_artifact(self.ARTIFACT_NAME)
        if content is None:
            return None

        try:
            return json.loads(content)
        except json.JSONDecodeError:
            return None

    def exists(self) -> bool:
        """Check if the artifact exists.

        Returns:
            True if the artifact exists, False otherwise.
        """
        return self.storage.artifact_exists(self.ARTIFACT_NAME)

    def get_exploitable(self) -> list[dict[str, Any]]:
        """Get only exploitable validation results.

        Returns:
            List of validation dicts where exploitable == True.
        """
        data = self.read()
        if data is None:
            return []

        validations = data.get("validations", [])
        return [v for v in validations if v.get("exploitable") is True]

    def get_exploitable_ids(self) -> set[str]:
        """Get the IDs of exploitable vulnerabilities.

        Returns:
            Set of vulnerability IDs that were confirmed exploitable.
        """
        exploitable = self.get_exploitable()
        return {v.get("vulnerability_id", "") for v in exploitable if v.get("vulnerability_id")}
